import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

@Injectable()
export class PdfService {

  async generateRecommendationsPDF(data: any): Promise<Buffer> {

    return new Promise((resolve, reject) => {

      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      const buffers: Uint8Array[] = [];

      doc.on('data', (chunk) => {
        buffers.push(chunk);
      });

      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });

      doc.on('error', (err) => {
        reject(err);
      });

      // =========================================
      // TITLE
      // =========================================

      doc
        .fontSize(22)
        .text('UniPillar Recommendation Report', {
          align: 'center',
        });

      doc.moveDown();

      // =========================================
      // PROFILE
      // =========================================

      const profile = data.profile;

      doc
        .fontSize(16)
        .text('Student Profile');

      doc.moveDown(0.5);

      doc.fontSize(12);

      doc.text(`JEE Main Rank: ${profile.mainCategoryRank}`);
      doc.text(`JEE Advanced Rank: ${profile.advCategoryRank}`);
      doc.text(`Category: ${profile.category}`);
      doc.text(`Home State: ${profile.homeState}`);
      doc.text(`Gender: ${profile.gender}`);

      doc.moveDown();

      // =========================================
      // PREFERENCES
      // =========================================

      doc
        .fontSize(16)
        .text('Preferences');

      doc.moveDown(0.5);

      doc.fontSize(12);

      doc.text(`Hometown Weight: ${data.weights.hometown}`);
      doc.text(`College Weight: ${data.weights.college}`);
      doc.text(`Branch Weight: ${data.weights.branch}`);

      doc.moveDown();

      // =========================================
      // BRANCHES
      // =========================================

      doc
        .fontSize(16)
        .text('Preferred Branches');

      doc.moveDown(0.5);

      data.branches.forEach((branch: string) => {
        doc.fontSize(12).text(`- ${branch}`);
      });

      doc.moveDown();

      // =========================================
      // RECOMMENDATIONS
      // =========================================

      doc
        .fontSize(18)
        .text('Recommended Colleges');

      doc.moveDown();

      const results = data.results || [];

      results.slice(0, 50).forEach((college: any, index: number) => {

        // automatic new page
        if (doc.y > 700) {
          doc.addPage();
        }

        doc
          .fontSize(14)
          .text(`${index + 1}. ${college.Institute}`);

        doc.fontSize(12);

        doc.text(`Branch: ${college.branch_shortcut || 'N/A'}`);

        doc.text(`Degree: ${college.degree_type || 'N/A'}`);

        doc.text(`State: ${college.college_state || 'N/A'}`);

        doc.text(
          `Closing Rank: ${
            college.predicted_closing_rank_2026 || 'N/A'
          }`
        );

        doc.text(
          `Admission Chance: ${
            college.admission_chance || 'N/A'
          }`
        );

        doc.text(
          `Score: ${
            Math.round(college.final_score || 0)
          }`
        );

        doc.moveDown();
      });

      // =========================================
      // FOOTER
      // =========================================

      doc.moveDown(2);

      doc
        .fontSize(10)
        .text(
          'Generated by UniPillar AI',
          {
            align: 'center',
          },
        );

      doc.end();
    });
  }
}